## Numpy Practice (0.5 point)

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
#1
import numpy as np

i = 10
mat1 = np.zeros((i - 2, i - 2))
mat1 = np.vstack((np.ones((1, i - 2)), mat1))
mat1 = np.vstack((mat1, np.ones((1, i - 2))))
mat1 = np.hstack((np.ones((i, 1)), mat1))
mat1 = np.hstack((mat1, np.ones((i, 1))))

np.array(mat1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [37]:
#2
i = 5
mat2 = np.arange(0, i, 1)
for _ in range(0, i - 1):
    mat = np.vstack((mat2, np.arange(0, i, 1)))

np.array(mat2)

array([0, 1, 2, 3, 4])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [38]:
#3
i = 8
mat3 = np.zeros((i, i))
for x in range(0, i):
    for y in range(0, i):
        if (x + y) % 2 == 0:
            mat3[x][y] = 1

np.array(mat3)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [39]:
#4
arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mat4 = arr4[arr4 % 2 == 0]

np.array(mat4)

array([0, 2, 4, 6, 8])

5. Normalize a 5x5 random matrix that follows the Gaussian distribution N(4,3).(Z-Score Normalization零均值归一化)

In [5]:
#5
arr5 = np.random.normal(3, 4, (5, 5))
mat5 = (arr5 - np.mean(arr5)) / np.std(arr5)
print(mat5)

[[-0.75473447  1.64130713  0.17956178  0.51056923  0.56059526]
 [-1.61737714  1.45520103 -1.24897792  0.11079218 -0.65078616]
 [ 0.56564539 -0.41483064 -0.14510247  0.74177212  0.08664771]
 [ 0.50059987  1.85180904 -0.90022919  1.13896009 -1.44807948]
 [ 1.33700815 -1.20820621 -1.30608586 -0.54529257 -0.44076687]]


6. Consider a random positive 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [41]:
#6
ori6 = np.random.random((2, 10))
print(f'X, Y:\n{ori6}')

r6 = np.sqrt(ori6[0] ** 2 + ori6[1] ** 2)
print(f'R:\n{r6}')

t6 = np.arctan(ori6[1] / ori6[0] * 180 / np.pi)
print(f'T:\n{t6}')

X, Y:
[[0.41751991 0.20295309 0.51623158 0.29299907 0.47333427 0.01037032
  0.66123855 0.73674969 0.63638488 0.24436302]
 [0.50729816 0.89911885 0.9141083  0.97025217 0.89694281 0.85254742
  0.63595742 0.0157484  0.49931316 0.17552505]]
R:
[0.65701926 0.92174002 1.04980428 1.01352737 1.0141754  0.85261049
 0.91743024 0.73691798 0.80888772 0.30086929]
T:
[1.55643279 1.56685671 1.56094011 1.56552579 1.56158614 1.57058403
 1.55265121 0.88606965 1.54855542 1.54650293]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [49]:
#7
i = 5
v7 = [1, 2, 3, 4, 5]
mat7 = np.zeros(4 * i - 3)
for x in range(0, i):
    mat7[4 * x] = v7[x]
print(mat7)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 

hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2)

First guess a result, then print the result, and finally find why

In [43]:
#8
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [ ]:
#9
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))